#!/usr/bin/env bash

sudo apt-get -y update
apt-get -y install haproxy

# edit config file
server_config=\
"
frontend  akoatem-frontend
        bind *:80
        mode http
        default_backend akoatem-backend
backend akoatem-backend
        balance roundrobin
        server 106489-web-01 34.232.68.152:80 check
        server 106489-web-02 3.83.227.80:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart

